<?xml version="1.0" encoding="UTF-8"?>
<testsuite hostname="Grievous-PC" name="serviceimpls.EmployeeServiceImplTestCase" tests="10" failures="1" timestamp="21 Jun 2011 18:02:19 GMT" time="4.374" errors="0">
  <testcase name="testCanCountAll" time="0.274" classname="serviceimpls.EmployeeServiceImplTestCase"/>
  <testcase name="testCanDeleteAll" time="0.319" classname="serviceimpls.EmployeeServiceImplTestCase"/>
  <testcase name="testCanFind" time="0.11" classname="serviceimpls.EmployeeServiceImplTestCase"/>
  <testcase name="testCanFindAll" time="0.211" classname="serviceimpls.EmployeeServiceImplTestCase"/>
  <testcase name="testCanInsert" time="0.105" classname="serviceimpls.EmployeeServiceImplTestCase"/>
  <testcase name="testCanRemoveById" time="0.21" classname="serviceimpls.EmployeeServiceImplTestCase"/>
  <testcase name="testCanUpdate" time="0.239" classname="serviceimpls.EmployeeServiceImplTestCase"/>
  <testcase name="testEmployeeServiceIsNotNull" time="0.0010" classname="serviceimpls.EmployeeServiceImplTestCase"/>
  <testcase name="testTheLies" time="0.0010" classname="serviceimpls.EmployeeServiceImplTestCase">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;true&amp;gt; but was:&amp;lt;false&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<true> but was:<false>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertTrue(Assert.java:37)
	at org.testng.Assert.assertTrue(Assert.java:47)
	at serviceimpls.EmployeeServiceImplTestCase.testTheLies(EmployeeServiceImplTestCase.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:76)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:178)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:191)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:666)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1147)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
	at org.testng.SuiteRunner.run(SuiteRunner.java:223)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1049)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:974)
	at org.testng.TestNG.run(TestNG.java:905)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:203)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:174)
]]>
    </failure>
  </testcase>
  <testcase name="testTheTruth" time="0.0020" classname="serviceimpls.EmployeeServiceImplTestCase"/>
</testsuite>
